---
# tasks file for ansible-role-reaction
- name: Install reaction for debian based OS
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install reaction for other OS
  import_tasks: all.yml
  when: ansible_facts['os_family'] != "Debian" 